version: '3.4'

services:
  apigateway.api:
    image: ${DOCKER_REGISTRY-}apigatewayapi
    build:
      context: .
      dockerfile: src/APIGateway/ApiGateway.API/Dockerfile

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Catalog/Catalog.API/Dockerfile


  discount.api:
    image: ${DOCKER_REGISTRY-}discountapi
    build:
      context: .
      dockerfile: src/Discount/Discount.API/Dockerfile


  orders.api:
    image: ${DOCKER_REGISTRY-}ordersapi
    build:
      context: .
      dockerfile: src/Ordering/Orders.API/Dockerfile


  shoppingcart.api:
    image: ${DOCKER_REGISTRY-}shoppingcartapi
    build:
      context: .
      dockerfile: src/ShoppingCart/ShoppingCart.API/Dockerfile

